### ISSUE TITLE
cuIBM runs on Colonial One: a lift drop over the end

### ISSUE THREAD

**Issue by mesnardo** [barbagroup/snake-repro#1]
Last weekend, I submitted some cuIBM simulations to Colonial One.
The objective was to check that using cuIBM with a different version of cusp would give slightly different results in the force coefficients.

I created three local cuIBM branches:
- `production-cusp-0.4.0`: current version of cuIBM (`master`) that uses the version 0.4.0 of cusp,
- `production-cusp-0.5.1`: current version of cuIBM (`master`) that uses the version 0.5.1 of cusp,
- `revision86-cusp-0.4.0`: version of cuIBM close to the one referenced by Anush on figShare.

More information about the branch `revision86-cusp-0.4.0`:
The figShare repository mentions that Anush used the revision 77 of cuIBM to run the flying-snake simulation with cuda-4.2, g++-4.1, and the revision 558 of the cusp library.
I looked at the revision 558 of cusp (state after 558 commits) and the `CHANGELOG` present in the repository of that time mention the version 0.3.1.
This version of cusp is not compatible with the oldest version of cuda on Colonial One which is 5.0.
A few commits after revision 77 on the cuIBM repository, there is an update of code to work with cusp-0.4.0 (some path to header files of cusp have changed).
Those few additional commits bring us to the revision 86 of cuIBM (state after 86 commits in the repository).

For the three branches, I used cuda-7.5, g++-4.9.2 (and either cusp-0.4.0 or cusp-0.5.1), to make the cuIBM executables on Colonial One.
For each executable, I run a simulation of the snake at angle-of-attack 35 degrees and Reynolds number 2000.
The three runs gave very close results for the force coefficients.
The force coefficients of the run using cusp-0.5.1 slightly diverge over the end of time-integration period (between 70 and 80 time-units). We can see in the following figure that compares the force coefficients between the simulations with cusp-0.4.0 and cusp-0.5.1:

![forcecoefficientscomparecusp040](https://cloud.githubusercontent.com/assets/5657080/15061402/ef94cb08-1302-11e6-8274-d91508da48dd.png)

The force coefficients generated by the `revision86-cusp-0.4.0` and the `production-0.4.0` branches are not distinguishable as we can see in the figure just below:

![forcecoefficientscomparecurrentcusp040](https://cloud.githubusercontent.com/assets/5657080/15061425/32475d26-1303-11e6-810e-ae6747008735.png)

But what is striking me is that the three simulations exhibit a lift-drop between 60 and 80 time-units.

What is this surprising me?
Because I have a cuIBM simulation from September 2015 where the mean lift coefficient maintains its high value over the entire simulation:

![forcecoefficientscomparekrishnanetal2014](https://cloud.githubusercontent.com/assets/5657080/15061443/50c8dc0c-1303-11e6-86b3-5c7858accec2.png)

For this one, I used the revision 77, adapted it to cusp-0.4.0, and used cuda-5.5.
If I compare this build with the one from the branch `revision86-cusp-0.4.0`, the differences are the version of cuda used, the version of g++ used, and the machine (or the type of device).

Is it possible that for this type of highly unsteady flow, the version of cuda affects that much the forces generated by the snake?

**Comment by labarba** [comment]
Note --- only difference between revision 77 and 86 is change to include header file for Cusp. No real change in the code.
